# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPfgNycFk7G13DeDiGbVtvhm2eOKruHL
"""



import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("train.csv")

"""# New Section"""

st.write(df.shape)

st.dataframe(df.head())

st.dataframe(df.info())

df["age"] = df["age"].astype(int)

for col in df.columns:
  numerical_features = ["ID", "age", "result"]
  if col not in numerical_features:
    st.write(col, df[col].unique())
    st.write("-"*50)

df = df.drop(columns=["ID", "age_desc"])

st.write(df["contry_of_res"].unique())

mapping = {
    "Viet Nam": "Vietnam",
    "AmericanSamoa": "United States",
    "Hong Kong": "China"
}


df["contry_of_res"] = df["contry_of_res"].replace(mapping)

st.write(df["contry_of_res"].unique())

st.write(df["Class/ASD"].value_counts())

st.dataframe(df.describe())

sns.histplot(df["age"], kde=True)
st.title("Distribution of Age")

age_mean = df["age"].mean()
age_median = df["age"].median()

st.write("Mean:", age_mean)
st.write("Median:", age_median)



plt.axvline(age_mean, color="red", linestyle="--", label="Mean")
plt.axvline(age_median, color="green", linestyle="-", label="Median")

plt.legend()

st.pyplot(plt)

sns.histplot(df["result"], kde=True)
plt.title("Distribution of result")


result_mean = df["result"].mean()
result_median = df["result"].median()

st.write("Mean:", result_mean)
st.write("Median:", result_median)


plt.axvline(result_mean, color="red", linestyle="--", label="Mean")
plt.axvline(result_median, color="green", linestyle="-", label="Median")

plt.legend()

st.pyplot(plt)

sns.boxplot(x=df["age"])
plt.title("Box Plot for Age")
plt.xlabel("Age")
st.pyplot(plt)

sns.boxplot(x=df["result"])
plt.title("Box Plot for result")
plt.xlabel("result")
st.pyplot(plt)

Q1 = df["age"].quantile(0.25)
Q3 = df["age"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
age_outliers = df[(df["age"] < lower_bound) | (df["age"] > upper_bound)]


st.write(len(age_outliers))

Q1 = df["result"].quantile(0.25)
Q3 = df["result"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
result_outliers = df[(df["result"] < lower_bound) | (df["result"] > upper_bound)]

st.write(len(result_outliers))

categorical_columns = ['A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score',
       'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'gender',
       'ethnicity', 'jaundice', 'austim', 'contry_of_res', 'used_app_before',
       'relation']

for col in categorical_columns:
  sns.countplot(x=df[col])
  plt.title(f"Count Plot for {col}")
  plt.xlabel(col)
  plt.ylabel("Count")
  st.pyplot(plt)

st.write(df["Class/ASD"].value_counts())

df["ethnicity"] = df["ethnicity"].replace({"?": "Others", "others": "Others"})

st.write(df["relation"].unique())

df["relation"] = df["relation"].replace(
    {"?": "Others",
     "Relative": "Others",
     "Parent": "Others",
     "Health care professional": "Others"}
)

st.write(df["relation"].unique())

st.dataframe(df.head())

object_columns = df.select_dtypes(include=["object"]).columns

st.write(object_columns)

encoders = {}


for column in object_columns:
  label_encoder = LabelEncoder()
  df[column] = label_encoder.fit_transform(df[column])
  encoders[column] = label_encoder

st.write(encoders)

plt.figure(figsize=(15, 15))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation heatmap")
st.pyplot(plt)

def replace_outliers_with_median(df, column):
  Q1 = df[column].quantile(0.25)
  Q3 = df[column].quantile(0.75)
  IQR = Q3 - Q1

  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR

  median = df[column].median()


  df[column] = df[column].apply(lambda x: median if x < lower_bound or x > upper_bound else x)

  return df

df = replace_outliers_with_median(df, "age")

df = replace_outliers_with_median(df, "result")

st.dataframe(df.head())

st.write(df.columns)

X = df.drop(columns=["Class/ASD"])
y = df["Class/ASD"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


st.write(y_train.shape)
st.write(y_test.shape)

st.write(y_train.value_counts())

st.write(y_test.value_counts())

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

st.write(y_train_smote.shape,end="\n")
st.write(y_train_smote.value_counts())

models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42)
}

cv_scores = {}


for model_name, model in models.items():
  st.write(f"Training {model_name} with default parameters...")
  scores = cross_val_score(model, X_train_smote, y_train_smote, cv=5, scoring="accuracy")
  cv_scores[model_name] = scores
  st.write(f"{model_name} Cross-Validation Accuracy: {np.mean(scores):.2f}")
  st.write("-"*50)

st.write(cv_scores)

decision_tree = DecisionTreeClassifier(random_state=42)
random_forest = RandomForestClassifier(random_state=42)
xgboost_classifier = XGBClassifier(random_state=42)

param_grid_dt = {
    "criterion": ["gini", "entropy"],
    "max_depth": [None, 10, 20, 30, 50, 70],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}


param_grid_rf = {
    "n_estimators": [50, 100, 200, 500],
    "max_depth": [None, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "bootstrap": [True, False]
}


param_grid_xgb = {
    "n_estimators": [50, 100, 200, 500],
    "max_depth": [3, 5, 7, 10],
    "learning_rate": [0.01, 0.1, 0.2, 0.3],
    "subsample": [0.5, 0.7, 1.0],
    "colsample_bytree": [0.5, 0.7, 1.0]
}

random_search_dt = RandomizedSearchCV(estimator=decision_tree, param_distributions=param_grid_dt, n_iter=20, cv=5, scoring='f1', random_state=42)
random_search_rf = RandomizedSearchCV(estimator=random_forest, param_distributions=param_grid_rf, n_iter=20, cv=5, scoring='f1', random_state=42)
random_search_xgb = RandomizedSearchCV(estimator=xgboost_classifier, param_distributions=param_grid_xgb, n_iter=20, cv=5, scoring='f1', random_state=42)

random_search_dt.fit(X_train_smote, y_train_smote)
random_search_rf.fit(X_train_smote, y_train_smote)
random_search_xgb.fit(X_train_smote, y_train_smote)

best_model = None
best_score = 0

if random_search_dt.best_score_ > best_score:
  best_model = random_search_dt.best_estimator_
  best_score = random_search_dt.best_score_

if random_search_rf.best_score_ > best_score:
  best_model = random_search_rf.best_estimator_
  best_score = random_search_rf.best_score_

if random_search_xgb.best_score_ > best_score:
  best_model = random_search_xgb.best_estimator_
  best_score = random_search_xgb.best_score_

st.write(f"Best Model: {best_model}")
st.write(f"Best Cross-Validation Accuracy: {best_score:.2f}")

y_test_pred = best_model.predict(X_test)
st.write("Accuracy score:\n", accuracy_score(y_test, y_test_pred))
st.write("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
st.write("Classification Report:\n", classification_report(y_test, y_test_pred, target_names=['No Autism','Autism']))
